workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t cv-release -f Dockerfile.gitlab .

test:
  stage: test
  script:
    - docker run cv-release /app/test.sh

deploy:
  stage: deploy
  script:
    - docker run cv-release /app/run.sh
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release/
      when: manual
