version: '3'

services:
  
  nginx1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-net
    
  nginx2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-net
  
  nginx3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-net
  
  load-balancer:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-balancer.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-net
    depends_on:
      - nginx1
      - nginx2
      - nginx3

networks:
  nginx-net:
    driver: bridge