name: Docker Build

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        default: latest
        description: image tag

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Images
    env:
      BUILDER_IMAGE: cv-builder
      RELEASE_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cv
      TAG: "${{ inputs.tag != '' && inputs.tag || github.ref_name }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build builder image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.BUILDER_IMAGE }}:${{ env.TAG }}
          target: builder

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build web image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.RELEASE_IMAGE }}:${{ env.TAG }}

    strategy:
      matrix:
        tags: [ '${{ github.ref }}', 'latest' ]
